"""Execution event schemas and types for observability and trace logging."""

import uuid
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import Field

from app.schemas.common import AegisBaseSchema, utc_now


class ExecutionEventType(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    RUN_STARTED = "RUN_STARTED"
    MODEL_CALL_STARTED = "MODEL_CALL_STARTED"
    MODEL_CALL_COMPLETED = "MODEL_CALL_COMPLETED"
    STATE_TRANSITION = "STATE_TRANSITION"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"

    # Tool Execution Events (Phase 2)
    TOOL_CALL_REQUESTED = "TOOL_CALL_REQUESTED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    TOOL_CALL_FAILED = "TOOL_CALL_FAILED"
    TOOL_CALL_TIMEOUT = "TOOL_CALL_TIMEOUT"
    TOOL_CALL_REJECTED = "TOOL_CALL_REJECTED"

    # Memory Engine Events (Phase 3)
    MEMORY_RETRIEVAL_STARTED = "MEMORY_RETRIEVAL_STARTED"
    MEMORY_RETRIEVAL_COMPLETED = "MEMORY_RETRIEVAL_COMPLETED"
    MEMORY_WRITE_STARTED = "MEMORY_WRITE_STARTED"
    MEMORY_WRITE_COMPLETED = "MEMORY_WRITE_COMPLETED"
    MEMORY_WRITE_REJECTED = "MEMORY_WRITE_REJECTED"
    MEMORY_DELETED = "MEMORY_DELETED"

    # Evaluation & Reflection Events (Phase 4)
    EVALUATION_STARTED = "EVALUATION_STARTED"
    EVALUATION_COMPLETED = "EVALUATION_COMPLETED"
    EVALUATION_FAILED = "EVALUATION_FAILED"
    REFLECTION_STARTED = "REFLECTION_STARTED"
    REFLECTION_COMPLETED = "REFLECTION_COMPLETED"
    REFLECTION_FAILED = "REFLECTION_FAILED"

    # Planner & Execution Graph Events (Phase 5)
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_VALIDATED = "PLAN_VALIDATED"
    PLAN_VALIDATION_FAILED = "PLAN_VALIDATION_FAILED"
    GRAPH_EXECUTION_STARTED = "GRAPH_EXECUTION_STARTED"
    GRAPH_EXECUTION_COMPLETED = "GRAPH_EXECUTION_COMPLETED"
    GRAPH_EXECUTION_FAILED = "GRAPH_EXECUTION_FAILED"
    NODE_READY = "NODE_READY"
    NODE_STARTED = "NODE_STARTED"
    NODE_COMPLETED = "NODE_COMPLETED"
    NODE_FAILED = "NODE_FAILED"
    NODE_RETRIED = "NODE_RETRIED"
    NODE_TIMEOUT = "NODE_TIMEOUT"
    NODE_SKIPPED = "NODE_SKIPPED"
    NODE_CANCELLED = "NODE_CANCELLED"
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    EXECUTION_RESUMED = "EXECUTION_RESUMED"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"

    # Controlled Autonomous Agent Loop Events (Phase 6)
    AGENT_LOOP_CREATED = "AGENT_LOOP_CREATED"
    AGENT_LOOP_STARTED = "AGENT_LOOP_STARTED"
    AGENT_ITERATION_STARTED = "AGENT_ITERATION_STARTED"
    AGENT_OBSERVATION_CREATED = "AGENT_OBSERVATION_CREATED"
    AGENT_DECISION_CREATED = "AGENT_DECISION_CREATED"
    AGENT_ITERATION_COMPLETED = "AGENT_ITERATION_COMPLETED"
    AGENT_LOOP_COMPLETED = "AGENT_LOOP_COMPLETED"
    AGENT_LOOP_FAILED = "AGENT_LOOP_FAILED"
    AGENT_LOOP_CANCELLED = "AGENT_LOOP_CANCELLED"
    AGENT_LOOP_BUDGET_EXCEEDED = "AGENT_LOOP_BUDGET_EXCEEDED"
    AGENT_LOOP_SAFETY_STOPPED = "AGENT_LOOP_SAFETY_STOPPED"
    AGENT_LOOP_STAGNATION_DETECTED = "AGENT_LOOP_STAGNATION_DETECTED"
    AGENT_LOOP_RESUMED = "AGENT_LOOP_RESUMED"

    # Multi-Agent Orchestration & Controlled Delegation Events (Phase 7)
    ORCHESTRATION_CREATED = "ORCHESTRATION_CREATED"
    ORCHESTRATION_STARTED = "ORCHESTRATION_STARTED"
    DELEGATION_PLAN_CREATED = "DELEGATION_PLAN_CREATED"
    WORKER_DISPATCHED = "WORKER_DISPATCHED"
    WORKER_STARTED = "WORKER_STARTED"
    WORKER_COMPLETED = "WORKER_COMPLETED"
    WORKER_FAILED = "WORKER_FAILED"
    WORKER_TIMEOUT = "WORKER_TIMEOUT"
    WORKER_CANCELLED = "WORKER_CANCELLED"
    WORKER_BLOCKED = "WORKER_BLOCKED"
    RESULT_COLLECTED = "RESULT_COLLECTED"
    RESULT_CONFLICT_DETECTED = "RESULT_CONFLICT_DETECTED"
    AGGREGATION_STARTED = "AGGREGATION_STARTED"
    AGGREGATION_COMPLETED = "AGGREGATION_COMPLETED"
    AGGREGATION_FAILED = "AGGREGATION_FAILED"
    REWORK_STARTED = "REWORK_STARTED"
    ORCHESTRATION_EVALUATED = "ORCHESTRATION_EVALUATED"
    ORCHESTRATION_COMPLETED = "ORCHESTRATION_COMPLETED"
    ORCHESTRATION_PARTIAL = "ORCHESTRATION_PARTIAL"
    ORCHESTRATION_FAILED = "ORCHESTRATION_FAILED"
    ORCHESTRATION_CANCELLED = "ORCHESTRATION_CANCELLED"
    ORCHESTRATION_BUDGET_EXCEEDED = "ORCHESTRATION_BUDGET_EXCEEDED"
    ORCHESTRATION_SAFETY_STOPPED = "ORCHESTRATION_SAFETY_STOPPED"
    ORCHESTRATION_RESUMED = "ORCHESTRATION_RESUMED"

    # Safety & Platform Hardening (Phase 8)
    SAFETY_ASSESSMENT_STARTED = "SAFETY_ASSESSMENT_STARTED"
    SAFETY_ASSESSMENT_COMPLETED = "SAFETY_ASSESSMENT_COMPLETED"
    SAFETY_GATE_PASSED = "SAFETY_GATE_PASSED"
    SAFETY_GATE_REJECTED = "SAFETY_GATE_REJECTED"
    SAFETY_APPROVAL_REQUESTED = "SAFETY_APPROVAL_REQUESTED"
    SAFETY_APPROVAL_GRANTED = "SAFETY_APPROVAL_GRANTED"
    SAFETY_APPROVAL_DENIED = "SAFETY_APPROVAL_DENIED"
    SAFETY_APPROVAL_EXPIRED = "SAFETY_APPROVAL_EXPIRED"
    SAFETY_TOKEN_REVOKED = "SAFETY_TOKEN_REVOKED"
    SAFETY_RATE_LIMITED = "SAFETY_RATE_LIMITED"
    SAFETY_CIRCUIT_OPENED = "SAFETY_CIRCUIT_OPENED"
    SAFETY_CIRCUIT_CLOSED = "SAFETY_CIRCUIT_CLOSED"
    SAFETY_STOP_TRIGGERED = "SAFETY_STOP_TRIGGERED"
    SAFETY_STOPPED = "SAFETY_STOPPED"
    SAFETY_POLICY_VIOLATION = "SAFETY_POLICY_VIOLATION"

    # Dynamic Authorization, RBAC, Token Scopes & Audit Attestation (Phase 9)
    AUTHORIZATION_CHECK_STARTED = "AUTHORIZATION_CHECK_STARTED"
    AUTHORIZATION_ALLOWED = "AUTHORIZATION_ALLOWED"
    AUTHORIZATION_DENIED = "AUTHORIZATION_DENIED"
    POLICY_EVALUATION_STARTED = "POLICY_EVALUATION_STARTED"
    POLICY_EVALUATION_COMPLETED = "POLICY_EVALUATION_COMPLETED"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"
    ROLE_REVOKED = "ROLE_REVOKED"
    POLICY_CHANGED = "POLICY_CHANGED"
    AUDIT_VERIFICATION_STARTED = "AUDIT_VERIFICATION_STARTED"
    AUDIT_VERIFICATION_COMPLETED = "AUDIT_VERIFICATION_COMPLETED"
    AUDIT_TAMPER_DETECTED = "AUDIT_TAMPER_DETECTED"

    # ABAC, CEL, Compliance & Signed Audit Checkpoints (Phase 10)
    ABAC_EVALUATION_STARTED = "ABAC_EVALUATION_STARTED"
    ABAC_EVALUATION_COMPLETED = "ABAC_EVALUATION_COMPLETED"
    POLICY_COMPILED = "POLICY_COMPILED"
    POLICY_COMPILATION_FAILED = "POLICY_COMPILATION_FAILED"
    POLICY_SIMULATION_REQUESTED = "POLICY_SIMULATION_REQUESTED"
    COMPLIANCE_REPORT_GENERATED = "COMPLIANCE_REPORT_GENERATED"
    COMPLIANCE_EVIDENCE_GENERATED = "COMPLIANCE_EVIDENCE_GENERATED"
    AUDIT_CHECKPOINT_CREATED = "AUDIT_CHECKPOINT_CREATED"
    AUDIT_CHECKPOINT_VERIFIED = "AUDIT_CHECKPOINT_VERIFIED"
    AUDIT_CHECKPOINT_FAILED = "AUDIT_CHECKPOINT_FAILED"


class ExecutionEvent(AegisBaseSchema):
    """
    Structured execution event emitted during agent run lifecycle.
    Guarantees monotonic sequence numbering within a run_id.
    """

    event_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    task_id: uuid.UUID
    run_id: uuid.UUID
    event_type: ExecutionEventType
    timestamp: datetime = Field(default_factory=utc_now)
    sequence_number: int = Field(
        ..., ge=1, description="Monotonically increasing sequence number within the run"
    )
    payload: dict[str, Any] = Field(
        default_factory=dict, description="Sanitized event metadata (no secrets)"
    )
